#!/bin/bash
#
# An easy way to find all existing videos that have been downloaded and run them through the 'fake-video' program.
################################################################################################

SEARCH_LOCATION='/nas/*/Movies'
LOG_FILE="fake-movie-paths.txt"
MIN_SIZE=30M
FILE_EXTENSIONS=(
    "mp4"
    "m4a"
    "avi"
    "m4v"
    "mpg"
    "mpeg"
    "wmv"
    "mkv"
)

# No need to edit below here.
################################################################################################

# Progress bar function
prog() {
    local w=50 p=$1;  shift
    printf -v dots "%*s" "$(( $p*$w/100 ))" ""; dots=${dots// /#};
    printf "\r\e[K|%-*s| %3d %% %s" "$w" "$dots" "$p" "$*";
}

NAME_ARGS=""
for i in "${FILE_EXTENSIONS[@]}"; do :
    if [[ -z "${NAME_ARGS// }" ]]; then
        NAME_ARGS="$i"
    else
        NAME_ARGS="$NAME_ARGS|$i"
    fi
done

echo -e "++ Bulk Fake Video Processor ++\n--------------------------------\n"
echo "Building file list - please be patient..."


SEARCH_COMMAND="find $SEARCH_LOCATION -type f -size +$MIN_SIZE -regextype posix-egrep -regex \".*\\.($NAME_ARGS)\$\" -print0"

process_movies=()
while IFS=  read -r -d $'\0'; do
    process_movies+=("$REPLY")
done < <(eval $SEARCH_COMMAND | sort -z )

count=0
total=`echo ${#process_movies[@]}`
echo -e "\nProcessing results:"

RED='\033[0;31m'
NC='\033[0m' # No Color

if [ "$total" -gt "100" ]; then
    SLOW_COMMENT="(this will take a while)"
fi
echo "Analyzing video in $total files $SLOW_COMMENT..."

for filename in "${process_movies[@]}"; do :

    count=$((count + 1))
    taskpercent=$((count*100/total))
    shortName="${filename##*/}"

    prog "$taskpercent" $shortName...
    ./fake-video --silent --log --video="$filename" 
    exitCode=$?

    if [ $exitCode -eq 1 ]; then

        prog "$taskpercent" ""
        echo -e "${RED}NOTICE: File was detected as a fake${NC} [$filename]"

        if [ ! -z "$LOG_FILE" ]; then
            echo "[$filename]" >> $LOG_FILE
        fi
    fi

done

echo ""
